---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.3
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 8000
    protocol: tcp
    targetPort: 8000
  selector:
    app: demo.44
  type: NodePort


#This is Deployment Configuration Kube definition
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo.44
  name: deployment.name.5
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 1
  selector:
    matchLabels:
      app: demo.44
  template:
    metadata:
      labels:
        app: demo.44
      namespace: default
    spec:
      containers:
      - imagePullPolicy: srinaths119/django:${buildNumber}
        ports:
        - containerPort: 8000
          name: portname.0
          protocol: tcp
      terminationGracePeriodSeconds: 0
