---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.0
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 8000
    protocol: tcp
    targetPort: 8000
  selector:
    app: demo.93
  type: NodePort

#This is Pod Configuration Kube definition
---
kind: Pod
metadata:
  labels:
    app: demo.93
  namespace: default
spec:
  containers:
  - imagePullPolicy: srinaths119/django:*
    ports:
    - containerPort: 8000
      name: portname.0
      protocol: tcp
  terminationGracePeriodSeconds: 0
