---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: django
spec:
  selector:
    matchLabels:
      app: django
  replicas: 2
  template:
    metadata:
      labels:
        app: django
    spec:
      containers:
      - name: myapp
        image: srinaths119/django:23
        ports:
        - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: django-service
spec:
  selector:
    app: django
  ports:
  - port: 8080
    protocol: TCP
    targetPort: 8080
  
