---
apiVersion: v1
kind: Service
metadata:
  annotations:
    generated.by: 8gwifi.org
  name: service.name.4
  namespace: default
spec:
  ports:
  - name: nameme_01
    port: 8000
    protocol: tcp
    targetPort: 8000
  selector:
    app: demo.25
  type: NodePort


#This is Deployment Configuration Kube definition
---
apiVersion: apps/v1beta1
kind: Deployment
metadata:
  labels:
    app: demo.25
  name: deployment.name.99
  namespace: default
spec:
  replicas: 2
