---
apiVersion: v1
kind: Service
metadata:
  name: django
spec:
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: NodePort
  selector:
    service: django
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: django
spec:
  replicas: 3
  template:
    metadata:
      labels:
        service: django
    spec:
      containers:
      - name: django
        image: srinaths119/django:${buildNumber}
        ports:
        - name: django
          containerPort: 8000
